### ISSUE TITLE
Add a more general "add_reflexives" function in Catlab

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/experiments#28]
From our earlier discussion on our model-stratification workflow sketch (based around this [notebook](https://github.com/DARPA-ASKEM/experiments/blob/main/notebooks/Nelson/multi-stratify-experiment/SIRV-Age-Travel-example.ipynb)), we'd need:
- [ ] a more general `add_reflexives` function that adds a transition with any dependent state node (not really a reflexive anymore), e.g. adding a `Vaccinate` transition node to a `Pop` state node should also add a required `Vaccine` state node (since `Vaccinate(Pop, Vaccine; Pop)`)
- [ ] the parent-child relationship between nodes of the base & strata models and those of the stratified model (currently we'd reverse engineer those relationships using the labels of the stratified model).

**Comment by p-stokes** [comment]
I think the functionality you're requesting in the first bullet point is better handled by simply re-specifying the model (which is actually what would be happening). In your particular example, if `add_reflexives` were to add new state nodes, there would be no way to know (without user specification) whether a single shared node should be added or unique node for each new transition. In other cases, there may also be issues with determining the ordering of inputs and/or outputs.

I'm not sure what you mean by the second bullet point. I'm thinking you want the preimage of the projection maps, but I'm not sure. Can you elaborate or give an example?
